version: '2'
services:
    tempus-client:
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
            args:
                MYGET: $MYGET_DUALOG_TOKEN
        image: tempus-client
        container_name: tempus-client
        ports:
            - "4200:80"
    tempus-api:
        build:
            context: ./Tempus.API
            dockerfile: Dockerfile
        image: tempus-api
        container_name: tempus-api
        ports:
            - "5000:80"
        environment:
            - TempusDBConnectionString
