version: '2'
services:
    tempus-client:
        build:
            context: ./ClientApp
            dockerfile: Dockerfile
            args:
                MYGET: $MYGET_DUALOG_TOKEN
        ports:
            - "4200:80"
    tempus-api:
        build:
            context: ./Tempus.API
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        environment:
            - TempusDBConnectionString
